/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AAdsousComparison extends PComparison
{
    private PAdsous _adsous_;

    public AAdsousComparison()
    {
        // Constructor
    }

    public AAdsousComparison(
        @SuppressWarnings("hiding") PAdsous _adsous_)
    {
        // Constructor
        setAdsous(_adsous_);

    }

    @Override
    public Object clone()
    {
        return new AAdsousComparison(
            cloneNode(this._adsous_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAdsousComparison(this);
    }

    public PAdsous getAdsous()
    {
        return this._adsous_;
    }

    public void setAdsous(PAdsous node)
    {
        if(this._adsous_ != null)
        {
            this._adsous_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._adsous_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._adsous_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._adsous_ == child)
        {
            this._adsous_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._adsous_ == oldChild)
        {
            setAdsous((PAdsous) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
