/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AAffInstr extends PInstr
{
    private PAffectation _affectation_;
    private TSemicol _semicol_;

    public AAffInstr()
    {
        // Constructor
    }

    public AAffInstr(
        @SuppressWarnings("hiding") PAffectation _affectation_,
        @SuppressWarnings("hiding") TSemicol _semicol_)
    {
        // Constructor
        setAffectation(_affectation_);

        setSemicol(_semicol_);

    }

    @Override
    public Object clone()
    {
        return new AAffInstr(
            cloneNode(this._affectation_),
            cloneNode(this._semicol_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAffInstr(this);
    }

    public PAffectation getAffectation()
    {
        return this._affectation_;
    }

    public void setAffectation(PAffectation node)
    {
        if(this._affectation_ != null)
        {
            this._affectation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._affectation_ = node;
    }

    public TSemicol getSemicol()
    {
        return this._semicol_;
    }

    public void setSemicol(TSemicol node)
    {
        if(this._semicol_ != null)
        {
            this._semicol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._affectation_)
            + toString(this._semicol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._affectation_ == child)
        {
            this._affectation_ = null;
            return;
        }

        if(this._semicol_ == child)
        {
            this._semicol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._affectation_ == oldChild)
        {
            setAffectation((PAffectation) newChild);
            return;
        }

        if(this._semicol_ == oldChild)
        {
            setSemicol((TSemicol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
