/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AAndExpr extends PExpr
{
    private PLogAnd _logAnd_;

    public AAndExpr()
    {
        // Constructor
    }

    public AAndExpr(
        @SuppressWarnings("hiding") PLogAnd _logAnd_)
    {
        // Constructor
        setLogAnd(_logAnd_);

    }

    @Override
    public Object clone()
    {
        return new AAndExpr(
            cloneNode(this._logAnd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndExpr(this);
    }

    public PLogAnd getLogAnd()
    {
        return this._logAnd_;
    }

    public void setLogAnd(PLogAnd node)
    {
        if(this._logAnd_ != null)
        {
            this._logAnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logAnd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logAnd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logAnd_ == child)
        {
            this._logAnd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logAnd_ == oldChild)
        {
            setLogAnd((PLogAnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
