/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ABloc extends PBloc
{
    private TLAcc _lAcc_;
    private PListInstr _listInstr_;
    private TRAcc _rAcc_;

    public ABloc()
    {
        // Constructor
    }

    public ABloc(
        @SuppressWarnings("hiding") TLAcc _lAcc_,
        @SuppressWarnings("hiding") PListInstr _listInstr_,
        @SuppressWarnings("hiding") TRAcc _rAcc_)
    {
        // Constructor
        setLAcc(_lAcc_);

        setListInstr(_listInstr_);

        setRAcc(_rAcc_);

    }

    @Override
    public Object clone()
    {
        return new ABloc(
            cloneNode(this._lAcc_),
            cloneNode(this._listInstr_),
            cloneNode(this._rAcc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABloc(this);
    }

    public TLAcc getLAcc()
    {
        return this._lAcc_;
    }

    public void setLAcc(TLAcc node)
    {
        if(this._lAcc_ != null)
        {
            this._lAcc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lAcc_ = node;
    }

    public PListInstr getListInstr()
    {
        return this._listInstr_;
    }

    public void setListInstr(PListInstr node)
    {
        if(this._listInstr_ != null)
        {
            this._listInstr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listInstr_ = node;
    }

    public TRAcc getRAcc()
    {
        return this._rAcc_;
    }

    public void setRAcc(TRAcc node)
    {
        if(this._rAcc_ != null)
        {
            this._rAcc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rAcc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lAcc_)
            + toString(this._listInstr_)
            + toString(this._rAcc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lAcc_ == child)
        {
            this._lAcc_ = null;
            return;
        }

        if(this._listInstr_ == child)
        {
            this._listInstr_ = null;
            return;
        }

        if(this._rAcc_ == child)
        {
            this._rAcc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lAcc_ == oldChild)
        {
            setLAcc((TLAcc) newChild);
            return;
        }

        if(this._listInstr_ == oldChild)
        {
            setListInstr((PListInstr) newChild);
            return;
        }

        if(this._rAcc_ == oldChild)
        {
            setRAcc((TRAcc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
