/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AConditionInstr extends PInstr
{
    private PCondElse _condElse_;

    public AConditionInstr()
    {
        // Constructor
    }

    public AConditionInstr(
        @SuppressWarnings("hiding") PCondElse _condElse_)
    {
        // Constructor
        setCondElse(_condElse_);

    }

    @Override
    public Object clone()
    {
        return new AConditionInstr(
            cloneNode(this._condElse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConditionInstr(this);
    }

    public PCondElse getCondElse()
    {
        return this._condElse_;
    }

    public void setCondElse(PCondElse node)
    {
        if(this._condElse_ != null)
        {
            this._condElse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condElse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._condElse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._condElse_ == child)
        {
            this._condElse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._condElse_ == oldChild)
        {
            setCondElse((PCondElse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
