/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADectabDecvar extends PDecvar
{
    private PDectab _dectab_;

    public ADectabDecvar()
    {
        // Constructor
    }

    public ADectabDecvar(
        @SuppressWarnings("hiding") PDectab _dectab_)
    {
        // Constructor
        setDectab(_dectab_);

    }

    @Override
    public Object clone()
    {
        return new ADectabDecvar(
            cloneNode(this._dectab_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADectabDecvar(this);
    }

    public PDectab getDectab()
    {
        return this._dectab_;
    }

    public void setDectab(PDectab node)
    {
        if(this._dectab_ != null)
        {
            this._dectab_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dectab_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dectab_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dectab_ == child)
        {
            this._dectab_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dectab_ == oldChild)
        {
            setDectab((PDectab) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
