/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADecfoncLDecfonc extends PLDecfonc
{
    private PDecfonc _decfonc_;

    public ADecfoncLDecfonc()
    {
        // Constructor
    }

    public ADecfoncLDecfonc(
        @SuppressWarnings("hiding") PDecfonc _decfonc_)
    {
        // Constructor
        setDecfonc(_decfonc_);

    }

    @Override
    public Object clone()
    {
        return new ADecfoncLDecfonc(
            cloneNode(this._decfonc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecfoncLDecfonc(this);
    }

    public PDecfonc getDecfonc()
    {
        return this._decfonc_;
    }

    public void setDecfonc(PDecfonc node)
    {
        if(this._decfonc_ != null)
        {
            this._decfonc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decfonc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decfonc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decfonc_ == child)
        {
            this._decfonc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decfonc_ == oldChild)
        {
            setDecfonc((PDecfonc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
