/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AEcrirePar extends PPar
{
    private PEcrireCall _ecrireCall_;

    public AEcrirePar()
    {
        // Constructor
    }

    public AEcrirePar(
        @SuppressWarnings("hiding") PEcrireCall _ecrireCall_)
    {
        // Constructor
        setEcrireCall(_ecrireCall_);

    }

    @Override
    public Object clone()
    {
        return new AEcrirePar(
            cloneNode(this._ecrireCall_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEcrirePar(this);
    }

    public PEcrireCall getEcrireCall()
    {
        return this._ecrireCall_;
    }

    public void setEcrireCall(PEcrireCall node)
    {
        if(this._ecrireCall_ != null)
        {
            this._ecrireCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ecrireCall_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ecrireCall_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ecrireCall_ == child)
        {
            this._ecrireCall_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ecrireCall_ == oldChild)
        {
            setEcrireCall((PEcrireCall) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
