/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AEcrireInstr extends PInstr
{
    private PEcrireCall _ecrireCall_;
    private TSemicol _semicol_;

    public AEcrireInstr()
    {
        // Constructor
    }

    public AEcrireInstr(
        @SuppressWarnings("hiding") PEcrireCall _ecrireCall_,
        @SuppressWarnings("hiding") TSemicol _semicol_)
    {
        // Constructor
        setEcrireCall(_ecrireCall_);

        setSemicol(_semicol_);

    }

    @Override
    public Object clone()
    {
        return new AEcrireInstr(
            cloneNode(this._ecrireCall_),
            cloneNode(this._semicol_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEcrireInstr(this);
    }

    public PEcrireCall getEcrireCall()
    {
        return this._ecrireCall_;
    }

    public void setEcrireCall(PEcrireCall node)
    {
        if(this._ecrireCall_ != null)
        {
            this._ecrireCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ecrireCall_ = node;
    }

    public TSemicol getSemicol()
    {
        return this._semicol_;
    }

    public void setSemicol(TSemicol node)
    {
        if(this._semicol_ != null)
        {
            this._semicol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ecrireCall_)
            + toString(this._semicol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ecrireCall_ == child)
        {
            this._ecrireCall_ = null;
            return;
        }

        if(this._semicol_ == child)
        {
            this._semicol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ecrireCall_ == oldChild)
        {
            setEcrireCall((PEcrireCall) newChild);
            return;
        }

        if(this._semicol_ == oldChild)
        {
            setSemicol((TSemicol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
