/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AEqualityComparison extends PComparison
{
    private PComparison _comparison_;
    private TEquals _equals_;
    private PAdsous _adsous_;

    public AEqualityComparison()
    {
        // Constructor
    }

    public AEqualityComparison(
        @SuppressWarnings("hiding") PComparison _comparison_,
        @SuppressWarnings("hiding") TEquals _equals_,
        @SuppressWarnings("hiding") PAdsous _adsous_)
    {
        // Constructor
        setComparison(_comparison_);

        setEquals(_equals_);

        setAdsous(_adsous_);

    }

    @Override
    public Object clone()
    {
        return new AEqualityComparison(
            cloneNode(this._comparison_),
            cloneNode(this._equals_),
            cloneNode(this._adsous_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqualityComparison(this);
    }

    public PComparison getComparison()
    {
        return this._comparison_;
    }

    public void setComparison(PComparison node)
    {
        if(this._comparison_ != null)
        {
            this._comparison_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comparison_ = node;
    }

    public TEquals getEquals()
    {
        return this._equals_;
    }

    public void setEquals(TEquals node)
    {
        if(this._equals_ != null)
        {
            this._equals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equals_ = node;
    }

    public PAdsous getAdsous()
    {
        return this._adsous_;
    }

    public void setAdsous(PAdsous node)
    {
        if(this._adsous_ != null)
        {
            this._adsous_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._adsous_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comparison_)
            + toString(this._equals_)
            + toString(this._adsous_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comparison_ == child)
        {
            this._comparison_ = null;
            return;
        }

        if(this._equals_ == child)
        {
            this._equals_ = null;
            return;
        }

        if(this._adsous_ == child)
        {
            this._adsous_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comparison_ == oldChild)
        {
            setComparison((PComparison) newChild);
            return;
        }

        if(this._equals_ == oldChild)
        {
            setEquals((TEquals) newChild);
            return;
        }

        if(this._adsous_ == oldChild)
        {
            setAdsous((PAdsous) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
