/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AFcallPar extends PPar
{
    private PFunctionCall _functionCall_;

    public AFcallPar()
    {
        // Constructor
    }

    public AFcallPar(
        @SuppressWarnings("hiding") PFunctionCall _functionCall_)
    {
        // Constructor
        setFunctionCall(_functionCall_);

    }

    @Override
    public Object clone()
    {
        return new AFcallPar(
            cloneNode(this._functionCall_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFcallPar(this);
    }

    public PFunctionCall getFunctionCall()
    {
        return this._functionCall_;
    }

    public void setFunctionCall(PFunctionCall node)
    {
        if(this._functionCall_ != null)
        {
            this._functionCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._functionCall_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._functionCall_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._functionCall_ == child)
        {
            this._functionCall_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._functionCall_ == oldChild)
        {
            setFunctionCall((PFunctionCall) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
