/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AFcallInstr extends PInstr
{
    private PFunctionCall _functionCall_;
    private TSemicol _semicol_;

    public AFcallInstr()
    {
        // Constructor
    }

    public AFcallInstr(
        @SuppressWarnings("hiding") PFunctionCall _functionCall_,
        @SuppressWarnings("hiding") TSemicol _semicol_)
    {
        // Constructor
        setFunctionCall(_functionCall_);

        setSemicol(_semicol_);

    }

    @Override
    public Object clone()
    {
        return new AFcallInstr(
            cloneNode(this._functionCall_),
            cloneNode(this._semicol_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFcallInstr(this);
    }

    public PFunctionCall getFunctionCall()
    {
        return this._functionCall_;
    }

    public void setFunctionCall(PFunctionCall node)
    {
        if(this._functionCall_ != null)
        {
            this._functionCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._functionCall_ = node;
    }

    public TSemicol getSemicol()
    {
        return this._semicol_;
    }

    public void setSemicol(TSemicol node)
    {
        if(this._semicol_ != null)
        {
            this._semicol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._functionCall_)
            + toString(this._semicol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._functionCall_ == child)
        {
            this._functionCall_ = null;
            return;
        }

        if(this._semicol_ == child)
        {
            this._semicol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._functionCall_ == oldChild)
        {
            setFunctionCall((PFunctionCall) newChild);
            return;
        }

        if(this._semicol_ == oldChild)
        {
            setSemicol((TSemicol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
