/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AIdentifTab extends PIdentifTab
{
    private TIdentif _identif_;
    private TLSqr _lSqr_;
    private PExpr _expr_;
    private TRSqr _rSqr_;

    public AIdentifTab()
    {
        // Constructor
    }

    public AIdentifTab(
        @SuppressWarnings("hiding") TIdentif _identif_,
        @SuppressWarnings("hiding") TLSqr _lSqr_,
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") TRSqr _rSqr_)
    {
        // Constructor
        setIdentif(_identif_);

        setLSqr(_lSqr_);

        setExpr(_expr_);

        setRSqr(_rSqr_);

    }

    @Override
    public Object clone()
    {
        return new AIdentifTab(
            cloneNode(this._identif_),
            cloneNode(this._lSqr_),
            cloneNode(this._expr_),
            cloneNode(this._rSqr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdentifTab(this);
    }

    public TIdentif getIdentif()
    {
        return this._identif_;
    }

    public void setIdentif(TIdentif node)
    {
        if(this._identif_ != null)
        {
            this._identif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identif_ = node;
    }

    public TLSqr getLSqr()
    {
        return this._lSqr_;
    }

    public void setLSqr(TLSqr node)
    {
        if(this._lSqr_ != null)
        {
            this._lSqr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lSqr_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public TRSqr getRSqr()
    {
        return this._rSqr_;
    }

    public void setRSqr(TRSqr node)
    {
        if(this._rSqr_ != null)
        {
            this._rSqr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rSqr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identif_)
            + toString(this._lSqr_)
            + toString(this._expr_)
            + toString(this._rSqr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identif_ == child)
        {
            this._identif_ = null;
            return;
        }

        if(this._lSqr_ == child)
        {
            this._lSqr_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._rSqr_ == child)
        {
            this._rSqr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identif_ == oldChild)
        {
            setIdentif((TIdentif) newChild);
            return;
        }

        if(this._lSqr_ == oldChild)
        {
            setLSqr((TLSqr) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._rSqr_ == oldChild)
        {
            setRSqr((TRSqr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
