/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALDecvar extends PLDecvar
{
    private PDecvar _decvar_;
    private TComma _comma_;
    private PLDecvar _lDecvar_;

    public ALDecvar()
    {
        // Constructor
    }

    public ALDecvar(
        @SuppressWarnings("hiding") PDecvar _decvar_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PLDecvar _lDecvar_)
    {
        // Constructor
        setDecvar(_decvar_);

        setComma(_comma_);

        setLDecvar(_lDecvar_);

    }

    @Override
    public Object clone()
    {
        return new ALDecvar(
            cloneNode(this._decvar_),
            cloneNode(this._comma_),
            cloneNode(this._lDecvar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALDecvar(this);
    }

    public PDecvar getDecvar()
    {
        return this._decvar_;
    }

    public void setDecvar(PDecvar node)
    {
        if(this._decvar_ != null)
        {
            this._decvar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decvar_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PLDecvar getLDecvar()
    {
        return this._lDecvar_;
    }

    public void setLDecvar(PLDecvar node)
    {
        if(this._lDecvar_ != null)
        {
            this._lDecvar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lDecvar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decvar_)
            + toString(this._comma_)
            + toString(this._lDecvar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decvar_ == child)
        {
            this._decvar_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._lDecvar_ == child)
        {
            this._lDecvar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decvar_ == oldChild)
        {
            setDecvar((PDecvar) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._lDecvar_ == oldChild)
        {
            setLDecvar((PLDecvar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
