/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALDecfonc extends PLDecfonc
{
    private PDecfonc _decfonc_;
    private PLDecfonc _lDecfonc_;

    public ALDecfonc()
    {
        // Constructor
    }

    public ALDecfonc(
        @SuppressWarnings("hiding") PDecfonc _decfonc_,
        @SuppressWarnings("hiding") PLDecfonc _lDecfonc_)
    {
        // Constructor
        setDecfonc(_decfonc_);

        setLDecfonc(_lDecfonc_);

    }

    @Override
    public Object clone()
    {
        return new ALDecfonc(
            cloneNode(this._decfonc_),
            cloneNode(this._lDecfonc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALDecfonc(this);
    }

    public PDecfonc getDecfonc()
    {
        return this._decfonc_;
    }

    public void setDecfonc(PDecfonc node)
    {
        if(this._decfonc_ != null)
        {
            this._decfonc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decfonc_ = node;
    }

    public PLDecfonc getLDecfonc()
    {
        return this._lDecfonc_;
    }

    public void setLDecfonc(PLDecfonc node)
    {
        if(this._lDecfonc_ != null)
        {
            this._lDecfonc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lDecfonc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decfonc_)
            + toString(this._lDecfonc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decfonc_ == child)
        {
            this._decfonc_ = null;
            return;
        }

        if(this._lDecfonc_ == child)
        {
            this._lDecfonc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decfonc_ == oldChild)
        {
            setDecfonc((PDecfonc) newChild);
            return;
        }

        if(this._lDecfonc_ == oldChild)
        {
            setLDecfonc((PLDecfonc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
