/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALireInstr extends PInstr
{
    private PLireCall _lireCall_;
    private TSemicol _semicol_;

    public ALireInstr()
    {
        // Constructor
    }

    public ALireInstr(
        @SuppressWarnings("hiding") PLireCall _lireCall_,
        @SuppressWarnings("hiding") TSemicol _semicol_)
    {
        // Constructor
        setLireCall(_lireCall_);

        setSemicol(_semicol_);

    }

    @Override
    public Object clone()
    {
        return new ALireInstr(
            cloneNode(this._lireCall_),
            cloneNode(this._semicol_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALireInstr(this);
    }

    public PLireCall getLireCall()
    {
        return this._lireCall_;
    }

    public void setLireCall(PLireCall node)
    {
        if(this._lireCall_ != null)
        {
            this._lireCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lireCall_ = node;
    }

    public TSemicol getSemicol()
    {
        return this._semicol_;
    }

    public void setSemicol(TSemicol node)
    {
        if(this._semicol_ != null)
        {
            this._semicol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lireCall_)
            + toString(this._semicol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lireCall_ == child)
        {
            this._lireCall_ = null;
            return;
        }

        if(this._semicol_ == child)
        {
            this._semicol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lireCall_ == oldChild)
        {
            setLireCall((PLireCall) newChild);
            return;
        }

        if(this._semicol_ == oldChild)
        {
            setSemicol((TSemicol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
