/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AListInstr extends PListInstr
{
    private PListInstr _listInstr_;
    private PInstr _instr_;

    public AListInstr()
    {
        // Constructor
    }

    public AListInstr(
        @SuppressWarnings("hiding") PListInstr _listInstr_,
        @SuppressWarnings("hiding") PInstr _instr_)
    {
        // Constructor
        setListInstr(_listInstr_);

        setInstr(_instr_);

    }

    @Override
    public Object clone()
    {
        return new AListInstr(
            cloneNode(this._listInstr_),
            cloneNode(this._instr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListInstr(this);
    }

    public PListInstr getListInstr()
    {
        return this._listInstr_;
    }

    public void setListInstr(PListInstr node)
    {
        if(this._listInstr_ != null)
        {
            this._listInstr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listInstr_ = node;
    }

    public PInstr getInstr()
    {
        return this._instr_;
    }

    public void setInstr(PInstr node)
    {
        if(this._instr_ != null)
        {
            this._instr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listInstr_)
            + toString(this._instr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listInstr_ == child)
        {
            this._listInstr_ = null;
            return;
        }

        if(this._instr_ == child)
        {
            this._instr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listInstr_ == oldChild)
        {
            setListInstr((PListInstr) newChild);
            return;
        }

        if(this._instr_ == oldChild)
        {
            setInstr((PInstr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
