/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AMultMultdiv extends PMultdiv
{
    private PMultdiv _multdiv_;
    private TMult _mult_;
    private PNeg _neg_;

    public AMultMultdiv()
    {
        // Constructor
    }

    public AMultMultdiv(
        @SuppressWarnings("hiding") PMultdiv _multdiv_,
        @SuppressWarnings("hiding") TMult _mult_,
        @SuppressWarnings("hiding") PNeg _neg_)
    {
        // Constructor
        setMultdiv(_multdiv_);

        setMult(_mult_);

        setNeg(_neg_);

    }

    @Override
    public Object clone()
    {
        return new AMultMultdiv(
            cloneNode(this._multdiv_),
            cloneNode(this._mult_),
            cloneNode(this._neg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultMultdiv(this);
    }

    public PMultdiv getMultdiv()
    {
        return this._multdiv_;
    }

    public void setMultdiv(PMultdiv node)
    {
        if(this._multdiv_ != null)
        {
            this._multdiv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multdiv_ = node;
    }

    public TMult getMult()
    {
        return this._mult_;
    }

    public void setMult(TMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    public PNeg getNeg()
    {
        return this._neg_;
    }

    public void setNeg(PNeg node)
    {
        if(this._neg_ != null)
        {
            this._neg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._neg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multdiv_)
            + toString(this._mult_)
            + toString(this._neg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multdiv_ == child)
        {
            this._multdiv_ = null;
            return;
        }

        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        if(this._neg_ == child)
        {
            this._neg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multdiv_ == oldChild)
        {
            setMultdiv((PMultdiv) newChild);
            return;
        }

        if(this._mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(this._neg_ == oldChild)
        {
            setNeg((PNeg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
