/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AMultdivAdsous extends PAdsous
{
    private PMultdiv _multdiv_;

    public AMultdivAdsous()
    {
        // Constructor
    }

    public AMultdivAdsous(
        @SuppressWarnings("hiding") PMultdiv _multdiv_)
    {
        // Constructor
        setMultdiv(_multdiv_);

    }

    @Override
    public Object clone()
    {
        return new AMultdivAdsous(
            cloneNode(this._multdiv_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultdivAdsous(this);
    }

    public PMultdiv getMultdiv()
    {
        return this._multdiv_;
    }

    public void setMultdiv(PMultdiv node)
    {
        if(this._multdiv_ != null)
        {
            this._multdiv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multdiv_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multdiv_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multdiv_ == child)
        {
            this._multdiv_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multdiv_ == oldChild)
        {
            setMultdiv((PMultdiv) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
