/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AParNeg extends PNeg
{
    private PPar _par_;

    public AParNeg()
    {
        // Constructor
    }

    public AParNeg(
        @SuppressWarnings("hiding") PPar _par_)
    {
        // Constructor
        setPar(_par_);

    }

    @Override
    public Object clone()
    {
        return new AParNeg(
            cloneNode(this._par_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParNeg(this);
    }

    public PPar getPar()
    {
        return this._par_;
    }

    public void setPar(PPar node)
    {
        if(this._par_ != null)
        {
            this._par_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._par_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._par_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._par_ == child)
        {
            this._par_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._par_ == oldChild)
        {
            setPar((PPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
