/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASousAdsous extends PAdsous
{
    private PAdsous _adsous_;
    private TMinus _minus_;
    private PMultdiv _multdiv_;

    public ASousAdsous()
    {
        // Constructor
    }

    public ASousAdsous(
        @SuppressWarnings("hiding") PAdsous _adsous_,
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PMultdiv _multdiv_)
    {
        // Constructor
        setAdsous(_adsous_);

        setMinus(_minus_);

        setMultdiv(_multdiv_);

    }

    @Override
    public Object clone()
    {
        return new ASousAdsous(
            cloneNode(this._adsous_),
            cloneNode(this._minus_),
            cloneNode(this._multdiv_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASousAdsous(this);
    }

    public PAdsous getAdsous()
    {
        return this._adsous_;
    }

    public void setAdsous(PAdsous node)
    {
        if(this._adsous_ != null)
        {
            this._adsous_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._adsous_ = node;
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PMultdiv getMultdiv()
    {
        return this._multdiv_;
    }

    public void setMultdiv(PMultdiv node)
    {
        if(this._multdiv_ != null)
        {
            this._multdiv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multdiv_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._adsous_)
            + toString(this._minus_)
            + toString(this._multdiv_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._adsous_ == child)
        {
            this._adsous_ = null;
            return;
        }

        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._multdiv_ == child)
        {
            this._multdiv_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._adsous_ == oldChild)
        {
            setAdsous((PAdsous) newChild);
            return;
        }

        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._multdiv_ == oldChild)
        {
            setMultdiv((PMultdiv) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
