/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TTest extends Token
{
    public TTest()
    {
        super.setText("test");
    }

    public TTest(int line, int pos)
    {
        super.setText("test");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTest(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTest(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTest text.");
    }
}
